### PR TITLE
adjust units of temperature variables

### PR DESCRIPTION
**Pull request by simonpcouch**
Transforming the temperature variables from degrees Celcius * 100 (as documented) to degrees Celcius, though the scales seem a bit off:

``` r
library(tidyverse)
library(forested)

forested %>% select(contains("temp"))
#> # A tibble: 7,107 × 5
#>    dew_temp temp_annual_mean temp_annual_min temp_annual_max temp_january_min
#>       <dbl>            <dbl>           <dbl>           <dbl>            <dbl>
#>  1     0.04             6.42           -8.32            12.9            -0.08
#>  2     6.4             10.6             1.4             15.8             5.44
#>  3     6.06            10.1             0.19            14.4             5.72
#>  4     4.43             9.86           -1.2             15.8             3.95
#>  5     1.06             7.72           -5.98            13.8             1.6 
#>  6     1.35             7.89           -6               14.7             1.12
#>  7     1.42             7.61           -5.76            14.2             0.99
#>  8     6.39            10.4             1.11            15.4             5.54
#>  9     6.5             10.9             1.75            15.6             6.2 
#> 10    -5.63             0.28          -10.5              5.1            -4.54
#> # ℹ 7,097 more rows

hist(forested$temp_annual_max)
```

<sup>Created on 2024-07-22 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Particularly the maxes are a good bit lower than I would have expected.

@graysonwhite, any insight?

### CODE REVIEW

**Comment by graysonwhite** [comment]
Yeah, these do look a bit low to me, as well. Not quite sure why, but one thing to note is that these are the 30-year average of max annual temp, starting at 1991. Our planet has warmed quite a bit since then, so maybe that older data is bringing down the max? You could also look into PRISM and how those data are collected, but I am not confident you'd find a satisfying answer.

**Comment by simonpcouch** [comment]
Thanks for the insight @graysonwhite. :) Will poke around a bit more.

**Comment by simonpcouch** [comment]
Will defer to you on how to move forward here, @hrfick.

**Comment by simonpcouch** [comment]
Ope, closes #4.

**Pull request merged**
